const fs=require('fs'), zlib=require('zlib'), path=require('path');
function unesc(s){return s.replace(/\\([nrtbf()\\])/g,(_,c)=>({n:'\n',r:'\r',t:'\t',b:'\b',f:'\f','(':'(',')':')','\\':'\\'}[c])).replace(/\\([0-7]{1,3})/g,(_,o)=>String.fromCharCode(parseInt(o,8)));}
function streams(file){const buf=fs.readFileSync(file);const s=buf.toString('latin1');const out=[];let idx=0;while((idx=s.indexOf('stream',idx))>=0){const dictStart=s.lastIndexOf('obj',idx);const dict=s.slice(Math.max(0,dictStart),idx);let start=idx+6+(s[idx+6]=='\r'&&s[idx+7]=='\n'?2:s[idx+6]=='\n'?1:0);const end=s.indexOf('endstream',start);if(end<0)break;const stream=buf.subarray(start,end-(buf[end-1]===10||buf[end-1]===13?1:0));if(/FlateDecode/.test(dict)){try{out.push(zlib.inflateSync(stream).toString('latin1'))}catch{}}idx=end+9}return out}
function extract(content,page){const re=/(?:1 0 0 1\s+(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s+Tm)|(?:(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s+Td)|(?:\((?:\\.|[^\\)])*\)\s*Tj)|(?:\[(.*?)\]\s*TJ)/gs;const words=[];let x=0,y=0,m;while((m=re.exec(content))){if(m[1]!=null){x=+m[1];y=+m[2];continue}if(m[3]!=null){x+=+m[3];y+=+m[4];continue}if(m[0].endsWith('Tj')){const raw=m[0].match(/\((?:\\.|[^\\)])*\)/)?.[0]||'()';const text=unesc(raw.slice(1,-1)).trim();if(text)words.push({page,x:+x.toFixed(2),y:+y.toFixed(2),text})}else if(m[5]!=null){const text=[...m[5].matchAll(/\((?:\\.|[^\\)])*\)/g)].map(mm=>unesc(mm[0].slice(1,-1))).join('').trim();if(text)words.push({page,x:+x.toFixed(2),y:+y.toFixed(2),text})}}return words}
function money(s){let raw=String(s||'').replace(/[DC*]/g,'').replace(/\s/g,''); raw=raw.replace(/\./g,'').replace(',','.'); return Math.abs(+raw)}
function infer(hist){const h=String(hist||''); if(/PIX\s*REC|REC\.OUTRA|RECEB|CR[ÉE]D|RESGATE|\bDEP\.?|DEPOS|LIQ\.COBRAN[ÇC]A/i.test(h))return 'entrada'; if(/PIX\s*EMIT|EMIT\.OUT|D[ÉE]B|TARIFA|JUROS|IOF|EMPR[ÉE]STIMO|CONV|PAGAMENTO/i.test(h))return 'saida'; return 'saida'}
const SKIP=/^(SALDO DO DIA|Data|Documento|Histórico|Valor|HISTÓRICO|RESUMO|ENCARGOS|OUTRAS|Sicoob|SISTEMA|PLATAFORMA|EXTRATO|Cooperativa|Conta:|Periodo:|Saldo |Cheque especial|Tarifas |SAC:|Taxa |Custo |Vencimento |Previsão |https?:|INFORMAÇ)/i;
function parse(file){const words=streams(file).flatMap((s,i)=>extract(s,i+1)); const rows=[]; for(const w of words){let r=rows.find(r=>r.page===w.page&&Math.abs(r.y-w.y)<3); if(!r){r={page:w.page,y:w.y,items:[]};rows.push(r)} r.items.push({x:w.x,text:w.text})} rows.sort((a,b)=>a.page-b.page||b.y-a.y); const structured=rows.map(r=>{const texts=r.items.sort((a,b)=>a.x-b.x); const date=texts.find(t=>t.x<130&&/^\d{2}\/\d{2}$/.test(t.text)); const valItems=texts.filter(t=>t.x>430); const valText=valItems.map(t=>t.text).join('').replace(/\s+/g,''); const m=valText.match(/\d{1,3}(?:\.\d{3})*,\d{2}[DC*]?|\d+,\d{2}[DC*]?/); const hist=texts.filter(t=>t.x>=130&&t.x<430).map(t=>t.text).join(' ').trim(); return {page:r.page,y:r.y,date:date?.text||null,val:m?.[0]||null,hist,isSkip:SKIP.test(hist)}});
 const tx=[]; const balances=[]; for(let i=0;i<structured.length;i++){const row=structured[i]; if(!row.date) continue; if(/SALDO (ANTERIOR|DO DIA|BLOQ)|SALDO BLOQ/i.test(row.hist||'')){ if(row.val && /[CD]$/.test(row.val)) balances.push({date:row.date,hist:row.hist,val:row.val}); continue;} if(row.isSkip) continue; let hist=row.hist, valStr=row.val; if(!valStr && i>0){const prev=structured[i-1]; if(!prev.date&&prev.val&&Math.abs(prev.y-row.y)<=8) valStr=prev.val;} if(!valStr && i+1<structured.length){const next=structured[i+1]; if(!next.date&&next.val){ if(next.hist) hist=(hist+' '+next.hist).trim(); valStr=next.val; i++; }} if(i+1<structured.length){const next=structured[i+1]; if(!next.date&&!next.val&&next.hist&&!next.isSkip){hist=(hist+' '+next.hist).trim(); i++;}}
 if(!valStr) continue; const tipo=/D$/.test(valStr)?'saida':/[C]$/.test(valStr)?'entrada':infer(hist); const v=money(valStr); if(!v) continue; tx.push({date:row.date,hist,val:valStr,tipo,v}); }
 const entradas=tx.filter(t=>t.tipo==='entrada').reduce((s,t)=>s+t.v,0); const saidas=tx.filter(t=>t.tipo==='saida').reduce((s,t)=>s+t.v,0); return {file:path.basename(file),count:tx.length,entradas:+entradas.toFixed(2),saidas:+saidas.toFixed(2),saldo:+(entradas-saidas).toFixed(2),balances,tx};}
for(const file of process.argv.slice(2)){const r=parse(file); const saldoAnt=r.balances.find(b=>/SALDO ANTERIOR/i.test(b.hist)); const saldoDia=[...r.balances].reverse().find(b=>/SALDO DO DIA/i.test(b.hist)); const ant=saldoAnt?money(saldoAnt.val)*(saldoAnt.val.endsWith('D')?-1:1):null; const fim=saldoDia?money(saldoDia.val)*(saldoDia.val.endsWith('D')?-1:1):null; const dif=ant!=null&&fim!=null?+(fim-ant-r.saldo).toFixed(2):null; console.log([r.file,r.count,r.entradas.toFixed(2),r.saidas.toFixed(2),r.saldo.toFixed(2), ant?.toFixed(2)??'', fim?.toFixed(2)??'', dif?.toFixed(2)??''].join('\t')); if(dif && Math.abs(dif)>0.011){console.log('  FURO?',r.tx.slice(-8));}}
